# Usage: add_trade_equations!(model, data, PAR)
# Paper-numbered LINKAGE trade equations.
# T-1--T-27 are the main nested Armington/CET/trade-margin system.
# T-28--T-34 are the paper's AIDS/alternative trade specification formulas retained in code form.

function add_trade_equations!(model, data::LinkageData, PAR)
    S=data.sets; default_sets!(data)
    i=S[:i]; j=S[:j]; h=S[:h]; f=S[:f]; r=S[:r]; rp=S[:rp]

    XA=model[:XA]; XAp=model[:XAp]; XAc=model[:XAc]; XAf=model[:XAf]
    XDd=model[:XDd]; XDs=model[:XDs]; XD=model[:XD]
    XMT=model[:XMT]; XM1=model[:XM1]; XM2=model[:XM2]
    PA=model[:PA]; PD=model[:PD]; PMT=model[:PMT]; PM1=model[:PM1]; PM2=model[:PM2]
    WTFd=model[:WTFd]; WTFs=model[:WTFs]; WTFin=model[:WTFin]; WTFout=model[:WTFout]; WTFq=model[:WTFq]
    TauPR=model[:TauPR]
    XP=model[:XP]; PP=model[:PP]; ES=model[:ES]; PET=model[:PET]; PE=model[:PE]
    WPE=model[:WPE]; WPM=model[:WPM]; PM=model[:PM]
    WXMg=model[:WXMg]; WPMg=model[:WPMg]; AXMg=model[:AXMg]; APMg=model[:APMg]; XMgr=model[:XMgr]

    # (T-1) Aggregate Armington demand: XA_i = Σ_j XAp_i,j + Σ_h XAc_i,h + Σ_f XAf_i,f.
    @constraint(model, T_1[ii in i], (XA[ii]) - (sum(XAp[ii,jj] for jj in j) + sum(XAc[ii,hh] for hh in h) + sum(XAf[ii,ff] for ff in f)) ⟂ XA[ii])

    # (T-2) Domestic component of Armington demand.
    @constraint(model, T_2[ii in i], (XDd[ii]) - (PAR[:beta_d][ii] * (PA[ii] / PD[ii])^PAR[:sigma_top_m][ii] * XA[ii]) ⟂ XDd[ii])

    # (T-3) Aggregate import component of Armington demand.
    @constraint(model, T_3[ii in i], (XMT[ii]) - (PAR[:beta_m][ii] * (PA[ii] / PMT[ii])^PAR[:sigma_top_m][ii] * XA[ii]) ⟂ XMT[ii])

    # (T-4) Armington dual price.
    @constraint(model, T_4[ii in i], (PA[ii]) - ((PAR[:beta_d][ii]*PD[ii]^(1-PAR[:sigma_top_m][ii]) + PAR[:beta_m][ii]*PMT[ii]^(1-PAR[:sigma_top_m][ii]))^(1/(1-PAR[:sigma_top_m][ii]))) ⟂ PA[ii])

    # (T-5) Top-tier composite import demand XM1.
    @constraint(model, T_5[rr in r, ii in i], (XM1[rr,ii]) - (PAR[:beta_1][(rr,ii)] * (PMT[ii] / PM1[rr,ii])^PAR[:sigma_w1][ii] * XMT[ii]) ⟂ XM1[rr,ii])

    # (T-6) Aggregate import price across top-tier sources.
    @constraint(model, T_6[ii in i], (PMT[ii]) - ((sum(PAR[:beta_1][(rr,ii)] * PM1[rr,ii]^(1-PAR[:sigma_w1][ii]) for rr in r))^(1/(1-PAR[:sigma_w1][ii]))) ⟂ PMT[ii])

    # (T-7) Second-tier composite import demand XM2.
    @constraint(model, T_7[rr in r, ii in i], (XM2[rr,ii]) - (PAR[:beta_2][(rr,ii)] * (PM1[rr,ii] / PM2[rr,ii])^PAR[:sigma_w2][(rr,ii)] * XM1[rr,ii]) ⟂ XM2[rr,ii])

    # (T-8) Top-tier composite import price PM1.
    @constraint(model, T_8[rr in r, ii in i], (PM1[rr,ii]) - ((sum(PAR[:beta_2][(rrp,ii)] * PM2[rrp,ii]^(1-PAR[:sigma_w2][(rr,ii)]) for rrp in rp))^(1/(1-PAR[:sigma_w2][(rr,ii)]))) ⟂ PM1[rr,ii])

    # (T-9) Bilateral import demand WTFd at the final Armington tier.
    @constraint(model, T_9[rr in r, rrp in rp, ii in i], (WTFd[rr,rrp,ii]) - (PAR[:beta_w][(rr,rrp,ii)] * (PM2[rrp,ii] / PM[rr,rrp,ii])^PAR[:sigma_w3][(rrp,ii)] * XM2[rrp,ii]) ⟂ WTFd[rr,rrp,ii])

    # (T-10) Second-tier import price PM2.
    @constraint(model, T_10[rrp in rp, ii in i], (PM2[rrp,ii]) - ((sum(PAR[:beta_w][(rr,rrp,ii)] * PM[rr,rrp,ii]^(1-PAR[:sigma_w3][(rrp,ii)]) for rr in r))^(1/(1-PAR[:sigma_w3][(rrp,ii)]))) ⟂ PM2[rrp,ii])

    # (T-11) TRQ in-quota complementarity written as inequality in JuMP.
    @constraint(model, T_11[rr in r, rrp in rp, ii in i], (WTFq[rr,rrp,ii]) - (WTFin[rr,rrp,ii]) ⟂ WTFq[rr,rrp,ii])

    # (T-12) TRQ premium upper bound.
    @constraint(model, T_12[rr in r, rrp in rp, ii in i], (PAR[:tau_out][(rr,rrp,ii)] - PAR[:tau_in][(rr,rrp,ii)]) - (TauPR[rr,rrp,ii]) ⟂ TauPR[rr,rrp,ii])

    # (T-13) Total bilateral imports equal in-quota plus over-quota imports.
    @constraint(model, T_13[rr in r, rrp in rp, ii in i], (WTFd[rr,rrp,ii]) - (WTFin[rr,rrp,ii] + WTFout[rr,rrp,ii]) ⟂ WTFd[rr,rrp,ii])

    # (T-14) Domestic supply allocation from CET top nest.
    @constraint(model, T_14[ii in i], (XDs[ii]) - (PAR[:beta_xd][ii] * (PD[ii] / PP[ii])^PAR[:sigma_z][ii] * (XP[ii] - XMgr[ii])) ⟂ XDs[ii])

    # (T-15) Aggregate export supply allocation from CET top nest.
    @constraint(model, T_15[ii in i], (ES[ii]) - (PAR[:beta_es][ii] * (PET[ii] / PP[ii])^PAR[:sigma_z][ii] * (XP[ii] - XMgr[ii])) ⟂ ES[ii])

    # (T-16) CET primal output aggregation for domestic and export supply.
    @constraint(model, T_16[ii in i], (XP[ii] - XMgr[ii]) - ((PAR[:beta_xd][ii]*XDs[ii]^((1+PAR[:sigma_z][ii])/PAR[:sigma_z][ii]) + PAR[:beta_es][ii]*ES[ii]^((1+PAR[:sigma_z][ii])/PAR[:sigma_z][ii]))^(PAR[:sigma_z][ii]/(1+PAR[:sigma_z][ii]))) ⟂ XP[ii])

    # (T-17) Average export price markup generated by TRQs.
    @constraint(model, T_17[rr in r, ii in i], (PET[ii] * ES[ii]) - (sum((PE[rr,rrp,ii] + PAR[:tau_trq_share][(rr,rrp,ii)]*TauPR[rr,rrp,ii]*WPM[rr,rrp,ii]) * WTFs[rr,rrp,ii] for rrp in rp)) ⟂ PET[ii])

    # (T-18) Bilateral export supply allocation across destinations.
    @constraint(model, T_18[rr in r, rrp in rp, ii in i], (WTFs[rr,rrp,ii]) - (PAR[:beta_z][(rr,rrp,ii)] * (PET[ii] / (PE[rr,rrp,ii] + PAR[:tau_trq_share][(rr,rrp,ii)]*TauPR[rr,rrp,ii]*WPM[rr,rrp,ii]))^PAR[:sigma_z2][ii] * ES[ii]) ⟂ WTFs[rr,rrp,ii])

    # (T-19) CET dual export price across destination markets.
    @constraint(model, T_19[rr in r, ii in i], (PET[ii]) - ((sum(PAR[:beta_z][(rr,rrp,ii)] * (PE[rr,rrp,ii] + PAR[:tau_trq_share][(rr,rrp,ii)]*TauPR[rr,rrp,ii]*WPM[rr,rrp,ii])^(1+PAR[:sigma_z2][ii]) for rrp in rp))^(1/(1+PAR[:sigma_z2][ii]))) ⟂ PET[ii])

    # (T-20) FOB export price including export tax/subsidy.
    @constraint(model, T_20[rr in r, rrp in rp, ii in i], (WPE[rr,rrp,ii]) - ((1 + PAR[:tau_e][(rr,rrp,ii)]) * PE[rr,rrp,ii]) ⟂ WPE[rr,rrp,ii])

    # (T-21) CIF import price with trade/transport margin and iceberg cost.
    @constraint(model, T_21[rr in r, rrp in rp, ii in i], (WPM[rr,rrp,ii]) - ((1 + PAR[:zeta_t][(rr,rrp,ii)]) * WPE[rr,rrp,ii] / PAR[:lambda_w][(rr,rrp,ii)]) ⟂ WPM[rr,rrp,ii])

    # (T-22) Domestic import price including tariff and TRQ premium.
    @constraint(model, T_22[rr in r, rrp in rp, ii in i], (PM[rr,rrp,ii]) - ((1 + PAR[:tau_m][(rr,rrp,ii)] + TauPR[rr,rrp,ii]) * WPM[rr,rrp,ii]) ⟂ PM[rr,rrp,ii])

    # (T-23) World demand for international trade and transport services.
    @constraint(model, T_23, (WPMg * WXMg) - (sum(PAR[:zeta_t][(rr,rrp,ii)] * WPE[rr,rrp,ii] * WTFd[rr,rrp,ii] for rr in r for rrp in rp for ii in i)) ⟂ WPMg)

    # (T-24) Regional demand for international trade and transport services.
    @constraint(model, T_24[rr in r], (AXMg[rr]) - (PAR[:alpha_TT][rr] * (WPMg / APMg[rr])^PAR[:sigma_TT] * WXMg) ⟂ AXMg[rr])

    # (T-25) World price of international trade and transport services.
    @constraint(model, T_25, (WPMg) - ((sum(PAR[:alpha_TT][rr] * APMg[rr]^(1-PAR[:sigma_TT]) for rr in r))^(1/(1-PAR[:sigma_TT]))) ⟂ WPMg)

    # (T-26) Local sectoral supply for trade and transport services.
    @constraint(model, T_26[rr in r, ii in i], (XMgr[ii]) - (PAR[:a_Mg][(rr,ii)] * AXMg[rr]) ⟂ XMgr[ii])

    # (T-27) Regional price of trade and transport services.
    @constraint(model, T_27[rr in r], (APMg[rr]) - (sum(PAR[:a_Mg][(rr,ii)] * PP[ii] for ii in i)) ⟂ APMg[rr])

    AIDSSH=model[:AIDSSH]; PMa=model[:PMa]; XDM=model[:XDM]; PDM=model[:PDM]

    # (T-28) AIDS import share relation.
    @constraint(model, T_28[rrp in rp, rr in r, ii in i], (AIDSSH[rrp,rr,ii]) - (PAR[:aids_alpha][(rrp,rr,ii)]
            + sum(PAR[:aids_gamma][(rrp,rrpp,rr,ii)] * log(PMa[rrpp,rr,ii]) for rrpp in rp)
            + PAR[:aids_beta][(rrp,rr,ii)] * log(XA[ii])) ⟂ AIDSSH[rrp,rr,ii])

    # (T-29) AIDS price index.
    @constraint(model, T_29[rr in r, ii in i], (log(PA[ii])) - (PAR[:aids_alpha0][(rr,ii)]
            + sum(PAR[:aids_alpha][(rrp,rr,ii)] * log(PMa[rrp,rr,ii]) for rrp in rp)
            + 0.5 * sum(PAR[:aids_gamma][(rrp,rrpp,rr,ii)] * log(PMa[rrp,rr,ii]) * log(PMa[rrpp,rr,ii]) for rrp in rp for rrpp in rp)) ⟂ PA[ii])

    # (T-30) Off-diagonal AIDS bilateral price equals standard import price.
    @constraint(model, T_30[rrp in rp, rr in r, ii in i; rrp != rr], (PMa[rrp,rr,ii]) - (PM[rrp,rr,ii]) ⟂ PMa[rrp,rr,ii])

    # (T-31) Diagonal AIDS composite demand.
    @constraint(model, T_31[rr in r, ii in i], (XDM[rr,ii]) - (AIDSSH[rr,rr,ii] * PA[ii] * XA[ii] / PMa[rr,rr,ii]) ⟂ XDM[rr,ii])

    # (T-32) Diagonal AIDS composite price.
    @constraint(model, T_32[rr in r, ii in i], (PDM[rr,ii]) - (PMa[rr,rr,ii]) ⟂ PDM[rr,ii])

    # (T-33) Domestic part of diagonal AIDS/CES composite.
    @constraint(model, T_33[rr in r, ii in i], (XDd[ii]) - (PAR[:alpha_dd][(rr,ii)] * (PDM[rr,ii] / PD[ii])^PAR[:sigma_b][(rr,ii)] * XDM[rr,ii]) ⟂ XDd[ii])

    # (T-34) Intra-regional bilateral flow part of diagonal AIDS/CES composite.
    @constraint(model, T_34[rr in r, ii in i], (WTFd[rr,rr,ii]) - (PAR[:alpha_dm][(rr,ii)] * (PDM[rr,ii] / PM[rr,rr,ii])^PAR[:sigma_b][(rr,ii)] * XDM[rr,ii]) ⟂ WTFd[rr,rr,ii])

    return model
end
